# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

import math

import pytest

from rtd_sensor import pt1000

# Independent reference values
# ----------------------------
#
# Primary source:
#   Italcoppie Sensori, "Pt1000 Resistance Chart"
#   Values according to DIN EN IEC 60751.
#
#   https://www.italcoppie.com/wp-content/uploads/2022/08/
#   Pt1000-Resistance-Chart-A4.pdf
#
# Accessed:
#   2026-08-08
#
# The published values are rounded to one decimal place. They are
# deliberately not generated by rtd_sensor.pt1000 and therefore provide
# an external check on the implementation.
#
# The rounded value 185.2 ohms is suitable for checking the forward
# conversion at -200 °C. It is not used as an inverse-conversion input
# because the exact IEC equation gives approximately 185.2008 ohms,
# making the rounded table value slightly lower than the mathematical
# minimum accepted by the model.


@pytest.mark.parametrize(
    ("temperature_c", "expected_resistance_ohms"),
    [
        (-200.0, 185.2),
        (-173.0, 300.7),
        (-150.0, 397.2),
        (-100.0, 602.6),
        (-50.0, 803.1),
        (0.0, 1000.0),
        (25.0, 1097.3),
        (50.0, 1194.0),
        (100.0, 1385.1),
        (200.0, 1758.6),
        (300.0, 2120.5),
        (500.0, 2809.8),
        (650.0, 3296.4),
        (850.0, 3904.8),
    ],
)
def test_celsius_to_resistance_matches_italcoppie_reference_table(
    temperature_c: float,
    expected_resistance_ohms: float,
) -> None:
    resistance = pt1000.celsius_to_resistance(temperature_c)

    assert resistance == pytest.approx(
        expected_resistance_ohms,
        abs=0.05,
    )


@pytest.mark.parametrize(
    ("resistance_ohms", "expected_temperature_c"),
    [
        (300.7, -173.0),
        (397.2, -150.0),
        (602.6, -100.0),
        (803.1, -50.0),
        (1000.0, 0.0),
        (1097.3, 25.0),
        (1194.0, 50.0),
        (1385.1, 100.0),
        (1758.6, 200.0),
        (2120.5, 300.0),
        (2809.8, 500.0),
        (3296.4, 650.0),
        (3904.8, 850.0),
    ],
)
def test_resistance_to_celsius_matches_italcoppie_reference_table(
    resistance_ohms: float,
    expected_temperature_c: float,
) -> None:
    temperature = pt1000.resistance_to_celsius(resistance_ohms)

    assert temperature == pytest.approx(
        expected_temperature_c,
        abs=0.02,
    )


@pytest.mark.parametrize(
    "temperature_c",
    [
        -200.0,
        -175.5,
        -100.0,
        -0.001,
        0.0,
        25.0,
        100.0,
        419.75,
        850.0,
    ],
)
def test_temperature_round_trip(temperature_c: float) -> None:
    resistance = pt1000.celsius_to_resistance(temperature_c)
    converted_temperature = pt1000.resistance_to_celsius(resistance)

    assert converted_temperature == pytest.approx(
        temperature_c,
        abs=1e-9,
    )


@pytest.mark.parametrize(
    "temperature_c",
    [
        -200.0,
        -150.0,
        -100.0,
        -50.0,
        0.0,
        100.0,
        300.0,
        600.0,
    ],
)
def test_resistance_increases_with_temperature(
    temperature_c: float,
) -> None:
    first = pt1000.celsius_to_resistance(temperature_c)
    second = pt1000.celsius_to_resistance(temperature_c + 0.001)

    assert second > first


@pytest.mark.parametrize(
    "temperature_c",
    [
        -201.0,
        851.0,
        math.inf,
        -math.inf,
        math.nan,
    ],
)
def test_celsius_to_resistance_rejects_invalid_temperature(
    temperature_c: float,
) -> None:
    with pytest.raises(ValueError):
        pt1000.celsius_to_resistance(temperature_c)


@pytest.mark.parametrize(
    "resistance_ohms",
    [
        -1.0,
        0.0,
        185.0,
        3905.0,
        math.inf,
        -math.inf,
        math.nan,
    ],
)
def test_resistance_to_celsius_rejects_invalid_resistance(
    resistance_ohms: float,
) -> None:
    with pytest.raises(ValueError):
        pt1000.resistance_to_celsius(resistance_ohms)


def test_minimum_temperature_boundary_round_trip() -> None:
    resistance = pt1000.celsius_to_resistance(pt1000.MIN_TEMPERATURE_C)

    temperature = pt1000.resistance_to_celsius(resistance)

    assert temperature == pytest.approx(
        pt1000.MIN_TEMPERATURE_C,
        abs=1e-9,
    )


def test_maximum_temperature_boundary_round_trip() -> None:
    resistance = pt1000.celsius_to_resistance(pt1000.MAX_TEMPERATURE_C)

    temperature = pt1000.resistance_to_celsius(resistance)

    assert temperature == pytest.approx(
        pt1000.MAX_TEMPERATURE_C,
        abs=1e-9,
    )


def test_zero_celsius_is_exactly_1000_ohms() -> None:
    assert pt1000.celsius_to_resistance(0.0) == 1000.0


def test_1000_ohms_is_zero_celsius() -> None:
    assert pt1000.resistance_to_celsius(1000.0) == 0.0
