# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

import math

import pytest

from rtd import pt500

# Independent reference values
# ----------------------------
#
# Primary validation source:
#   UST Umweltsensortechnik GmbH,
#   "Platinum thinfilm temperature sensor elements - Pt500 series",
#   "Pt500 (R0 = 500 ohm) - Basic resistance values".
#
#   https://www.umweltsensortechnik.de/fileadmin/assets/downloads/
#   platin/datenblaetter/pt500-basic-resistance-values-202201-Rev00.pdf
#
# Accessed:
#   2026-08-10
#
# The document states that its values are calculated according to
# DIN EN 60751 and publishes the same A/B/C coefficients used by the
# IEC PT-385 characteristic. Published resistance values are rounded
# to 0.01 ohm, so the test tolerance reflects that source precision.
# These values are not generated by rtd.pt500 and therefore provide
# an independent check of the implementation.
#
# Secondary cross-check:
#   Fluke PT100 Resistance Table Generator explicitly supports Pt500
#   tables using the PT-385 coefficients from IEC 60751.


@pytest.mark.parametrize(
    ("temperature_c", "expected_resistance_ohms"),
    [
        (-200.0, 92.60),
        (-150.0, 198.62),
        (-100.0, 301.28),
        (-50.0, 401.53),
        (0.0, 500.00),
        (25.0, 548.67),
        (50.0, 596.99),
        (100.0, 692.53),
        (200.0, 879.28),
        (300.0, 1060.26),
        (500.0, 1404.89),
        (650.0, 1648.20),
        (850.0, 1952.41),
    ],
)
def test_celsius_to_resistance_matches_ust_reference_table(
    temperature_c: float,
    expected_resistance_ohms: float,
) -> None:
    assert pt500.celsius_to_resistance(temperature_c) == pytest.approx(
        expected_resistance_ohms,
        abs=0.005,
    )


@pytest.mark.parametrize(
    ("resistance_ohms", "expected_temperature_c"),
    [
        (198.62, -150.0),
        (301.28, -100.0),
        (401.53, -50.0),
        (500.00, 0.0),
        (548.67, 25.0),
        (596.99, 50.0),
        (692.53, 100.0),
        (879.28, 200.0),
        (1060.26, 300.0),
        (1404.89, 500.0),
        (1648.20, 650.0),
    ],
)
def test_resistance_to_celsius_matches_ust_reference_table(
    resistance_ohms: float,
    expected_temperature_c: float,
) -> None:
    assert pt500.resistance_to_celsius(resistance_ohms) == pytest.approx(
        expected_temperature_c,
        abs=0.005,
    )


@pytest.mark.parametrize(
    "temperature_c",
    [-200.0, -175.5, -100.0, -0.001, 0.0, 25.0, 100.0, 419.75, 850.0],
)
def test_temperature_round_trip(temperature_c: float) -> None:
    resistance = pt500.celsius_to_resistance(temperature_c)
    converted = pt500.resistance_to_celsius(resistance)

    assert converted == pytest.approx(temperature_c, abs=1e-9)


@pytest.mark.parametrize(
    "temperature_c",
    [-200.0, -150.0, -100.0, -50.0, 0.0, 100.0, 300.0, 600.0],
)
def test_resistance_increases_with_temperature(temperature_c: float) -> None:
    first = pt500.celsius_to_resistance(temperature_c)
    second = pt500.celsius_to_resistance(temperature_c + 0.001)
    assert second > first


@pytest.mark.parametrize(
    "temperature_c",
    [-201.0, 851.0, math.inf, -math.inf, math.nan],
)
def test_celsius_to_resistance_rejects_invalid_temperature(
    temperature_c: float,
) -> None:
    with pytest.raises(ValueError):
        pt500.celsius_to_resistance(temperature_c)


@pytest.mark.parametrize(
    "resistance_ohms",
    [-1.0, 0.0, 92.0, 1953.0, math.inf, -math.inf, math.nan],
)
def test_resistance_to_celsius_rejects_invalid_resistance(
    resistance_ohms: float,
) -> None:
    with pytest.raises(ValueError):
        pt500.resistance_to_celsius(resistance_ohms)


def test_minimum_temperature_boundary_round_trip() -> None:
    resistance = pt500.celsius_to_resistance(pt500.MIN_TEMPERATURE_C)
    temperature = pt500.resistance_to_celsius(resistance)
    assert temperature == pytest.approx(pt500.MIN_TEMPERATURE_C, abs=1e-9)


def test_maximum_temperature_boundary_round_trip() -> None:
    resistance = pt500.celsius_to_resistance(pt500.MAX_TEMPERATURE_C)
    temperature = pt500.resistance_to_celsius(resistance)
    assert temperature == pytest.approx(pt500.MAX_TEMPERATURE_C, abs=1e-9)


def test_zero_celsius_is_exactly_500_ohms() -> None:
    assert pt500.celsius_to_resistance(0.0) == 500.0


def test_500_ohms_is_zero_celsius() -> None:
    assert pt500.resistance_to_celsius(500.0) == 0.0


@pytest.mark.parametrize(
    "temperature_c",
    [-200.0, -100.0, -0.001, 0.0, 25.0, 100.0, 850.0],
)
def test_pt500_is_five_times_pt100_on_same_iec_curve(
    temperature_c: float,
) -> None:
    from rtd import pt100

    assert pt500.celsius_to_resistance(temperature_c) == pytest.approx(
        5.0 * pt100.celsius_to_resistance(temperature_c),
        abs=1e-12,
    )


@pytest.mark.parametrize(
    "temperature_c",
    [-200.0, -100.0, 0.0, 100.0, 500.0, 850.0],
)
def test_pt500_sensitivity_scales_from_pt100(temperature_c: float) -> None:
    from rtd import pt100

    assert pt500.resistance_sensitivity_ohms_per_celsius(
        temperature_c
    ) == pytest.approx(
        5.0 * pt100.resistance_sensitivity_ohms_per_celsius(temperature_c),
        abs=1e-15,
    )
    assert pt500.temperature_sensitivity_celsius_per_ohm(
        temperature_c
    ) == pytest.approx(
        pt100.temperature_sensitivity_celsius_per_ohm(temperature_c) / 5.0,
        abs=1e-15,
    )
